### ISSUE TITLE
`spacetime login --server-issued-login` always saves the default `127.0.0.1:3000` in `cli.toml`

### ISSUE THREAD

**Issue by dare3path** [clockworklabs/SpacetimeDB#2512]
### Description
When I use the `spacetime login --server-issued-login` command, a file is created in `~/.config/spacetime/cli.toml` but it retains the default server configuration instead of updating it with the specified server details. As a result, subsequent commands like `spacetime publish` fail to connect to the correct server.

### Steps to Reproduce
1. Run the command: 
   ```sh
   spacetime login --server-issued-login http://127.1.2.3:6543
   ```
2. Check the contents of `~/.config/spacetime/cli.toml`.

### Expected Behavior
The `cli.toml` file should be updated with the specified server details:
```toml
default_server = "local"
spacetimedb_token = "..."

[[server_configs]]
nickname = "local"
host = "127.1.2.3:6543"
protocol = "http"

[[server_configs]]
nickname = "maincloud"
host = "maincloud.spacetimedb.com"
protocol = "https"
```

### Actual Behavior
The `cli.toml` file retains the default configuration:
```toml
default_server = "local"
spacetimedb_token = "..."

[[server_configs]]
nickname = "local"
host = "127.0.0.1:3000"
protocol = "http"

[[server_configs]]
nickname = "maincloud"
host = "maincloud.spacetimedb.com"
protocol = "https"
```

### Additional Context
https://github.com/clockworklabs/SpacetimeDB/blob/ee7970e75220a5255afe9c63642334407b91a35e/crates/cli/src/subcommands/login.rs#L48-L72

https://github.com/clockworklabs/SpacetimeDB/blob/ee7970e75220a5255afe9c63642334407b91a35e/crates/cli/src/config.rs#L646-L735
